### ISSUE TITLE
After opening "save file as..." -dialog it's not possible to input with "Japanese - Anthy"

### ISSUE THREAD

**Issue by DarkTrick** [ibus/ibus-anthy#14]
Which distribution and version?:
xubuntu 18.04, 19.04

Which desktop environment and version?:
xfce4: 4.12

Which session type?:
x11, I believe (output: command not found)

Which application and version?:
thunar 1.8.4
<any app, that calls the native "save file as..." dialog>

IBus version?:
1.5.19

ibus-anthy version?:
1.5.10

Issue description:
After opening "save file as..."-dialog it's not possible to do Japanese input.

Steps to reproduce:
1. Open (e.g.) mousepad 
2. Menu -> File -> Save as....
3. <Dialog opens>
4. Press [esc] for closing the dialog
5. Try to write something in mousepad

expected:
6. Writing something is possible

actual:
6. No input is processed

Can you reproduce your problem when you restart ibus-daemon? (yes / no):
yes, but it's not reproducible securely (= not every time I do the steps, it happens)

Do you see any errors when you run ibus-daemon with the verbose option?:
I can't really test this, because the quitting ibus and recalling it with `ibus-daemon --xim --verbose &` seems to cause several problems on my system (crashing firefox, crashing terminal on desktop change, freezing complete user session after a while)

Can you reproduce your problem with a new user account instead of the current your account?
No 
( It's probably several factors working together. I couldn't reproduce this on a fresh system with only ibus and ibus-anthy installed)

**Comment by fujiwarat** [comment]
How about using gedit?

**Comment by DarkTrick** [comment]
I'll close this bug for now. The problem still exists, but the trigger point is different.
It seems like there is something inherently wrong within Anthy, that - in certain situations - makes it keep input in a queue.
