### ISSUE TITLE
"Python" -> "Pythoん": "n" at the end of an English word becomes ん

### ISSUE THREAD

**Issue by DarkTrick** [ibus/ibus-anthy#18]
Which distribution and version?: 
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

Which desktop environment and version?: 
XFCE4.14

Which session type?: 
X11

IBus version?: 
1.5.21

ibus-anthy version?: 
1.5.10-2

Issue description:
"n" is not processed as expected

Steps to reproduce:
1.  Prepare a random input field
1.  Got to JP input mode
1.  type "Python", press Enter

Expected:
"Python" will be displayed.

Acutal:
"Pythoん" will be displayed.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Runo

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
not tried

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.
Which typing mode did you select? Eisu, Hiragana, Hull-width Eisu?

**Comment by DarkTrick** [comment]
Input Mode: Hiragana, Full-Width

**Comment by fujiwarat** [comment]
> Which version did you test on?

We treat upstream repo only. You should test both down stream Ubuntu and upstream before you file upstream.

**Comment by fujiwarat** [comment]
Did you enable `"Switch "Hiragana" and "Latin" with Shift key...` check button in "Conversion" tab in ibus-setup-anthy?

**Comment by DarkTrick** [comment]
- I'm not sure what 'upstream' in this context means. 
- I have a clean installation without any special settings: `apt-get install ibus-anthy`.
  - Switch "Hiragana" and "Latin" with Shift key and Hir... in preedit is set

**Comment by fujiwarat** [comment]
Upstream is here and the code is https://github.com/ibus/ibus-anthy.git which is not downstream Ubuntsu ibus-anthy.

**Comment by DarkTrick** [comment]
So I file downstream then. Thank you.
