### ISSUE TITLE
[Suggestion] Adding Description of Forked Anthy

### ISSUE THREAD

**Issue by WhiteCat6142** [ibus/ibus-anthy#22]
[Suggestion] Adding Description of Forked Anthy

Original anthy is very old.
The latest version released in 2009, almost 12 years ago.
So I suggest the following forked version.
I tried to build this one and fujiwarat/ibus-anthy, then they works great.
Add some notices to ibus-anthy 's README, please.

(still maintained in 2021 Feb)
Download
http://www.fenix.ne.jp/~G-HAL/soft/nosettle/im.html#anthy

Developent log
http://www.fenix.ne.jp/~G-HAL/soft/nosettle/anthy.html

License: LGPL,GPL,BSD depend on files

**Comment by fujiwarat** [comment]
Thank you for the notice.
But why do you need to update ibus-anthy's README officially? I guess you can bookmark it for yourself.
I recommend to use [anthy-unicode](https://github.com/fujiwarat/anthy-unicode/) instead of anthy and I think I need to port the patches.

**Comment by WhiteCat6142** [comment]
Thank for replying.
I just want to promote forked-anthy which is still mintained, because many people think "Anthy is an old software, no longer in use".
Then I thought README could be helpful to inform them. That is all.
