### ISSUE TITLE
PageUp/PageDown do not work to scroll candidates

### ISSUE THREAD

**Issue by uneyama** [ibus/ibus-anthy#27]
Hello, I recently installed AlmaLinux 8.5 and set-up ibus-anthy 1.5.13 on it by installing ibus-anthy-1.5.13-3.el8.x86_64.rpm and related packages. I wrote a simple script and run ibus-daemon on FVWM 2.6.9. ibus-anthy works on my FVWM environment, and I can input and convert Japanese. However, I found that PageUp and PageDown do not work. The detailed information and my workaround are as follows.

Which desktop environment and version?: FVWM 2.6.9

Which session type?: X11

Which application and version?: rxvt, emacs, and all of other applications on X

IBus version?: 1.5.19 (ibus-1.5.19-14.el8_5.x86_64.rpm)

ibus-anthy version?: 1.5.13 (ibus-anthy-1.5.13-3.el8.x86_64.rpm)

Issue description: PageUp and PageDown do not work to scroll candidates shown in a table.

Steps to reproduce:
1. Install ibus, ibus-anthy and related packages from EPEL.
2. Setup some environmental variables (such as $XMODIFIERS and $XIM). 
3. Run ibus-daemon as "ibus-daemon --xim -d"
4. Try to convert Japanese into Kanji, and open a look-up table
5. Push Page-Up (or Page-Down) key. (I expect the table should scroll.)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Do you see any errors when you run ibus-daemon with the verbose option?: yes, I saw the following error messages.
Error command: _Engine__cmd_candidates_page_up: IBus.Engine.page_up() takes exactly 1 argument (0 given)
Error command: _Engine__cmd_candidates_page_down: IBus.Engine.page_down() takes exactly 1 argument (0 given)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): I have not tried

Workaround: I found that the problem seems to be due to the handling of PageUp and PageDown signals in "engine/python3/engine.py". I tried to modify it, and found that if we replace "self.do_page_up()" (or "self.do_page_down()") by "self.__page_up(0)" ("self.__page_down(0)"), the PageUp key works. "__page_up()" function (or "__page_up()" function) requires one argument (although it seems not to be used) and thus I put a dummy value "0". The following attached file is a simple patch for engine.py. Although it seems to work at least on my environment, I'm not sure whether it works on other environments or not.
[ibus-anthy-1.5.13-engine_page_up_down.patch.txt](https://github.com/ibus/ibus-anthy/files/8481069/ibus-anthy-1.5.13-engine_page_up_down.patch.txt)

**Comment by fujiwarat** [comment]
Sorry for not noticing this issue.
I fixed this issue in the devel repo and will release 1.5.15 later.
https://github.com/fujiwarat/ibus-anthy/commit/63e441da978b8efd2aeeecfa9eed3155e4ed5fc6

**Comment by uneyama** [comment]
Thank you very much!
