### ISSUE TITLE
An option for Japanese thumb shift users to "commit" after "。" and "、"

### ISSUE THREAD

**Issue by Lifelabo** [ibus/ibus-anthy#3]
ibus-anthy has an option to input Japanese via thumb shift.

Many thumb shift users prefer to always "commit" ("kakutei") after "。" and "、" so that there is not need to commit after "。" or "、". If they want to convert ("henkan") the string, they convert before inputting "。" or "、".

Please create an option setting for Japanese thumb shift users to always "commit" after "。" and "、".
This may be done by automatically performing "commit" after  "。" or "、".

**Comment by Lifelabo** [comment]
The above can be achieved by modifying /usr/share/ibus-anthy/engine/engine.py as follows.
```
        def insert(keyval):
            try:
                self._MM = self._SS = 0
                ret = self.__on_key_common(ord(keyval))
                if (keyval in u',.、。' and
                    self.__prefs.get_value('common', 'behavior_on_period')):
-                   return self.__cmd_convert(keyval, state)
+                   return self.__cmd_convert(keyval, state)
                return ret
            except:
                pass
```

**Comment by fujiwarat** [comment]
I thought "Automatically convert" would be enough for the submitter.
Talking off line, I understood the auto-commit is still a valid request.
He can convert the preedit text before enter delimiters.

**Comment by fujiwarat** [comment]
Committed the patch.
https://github.com/fujiwarat/ibus-anthy/commit/0fc8cc7eff39a8fe7f1689affa47fdc779570df5
