### ISSUE TITLE
Compose key no longer works

### ISSUE THREAD

**Issue by spinnylights** [ibus/ibus-anthy#34]
Which distribution and version?: 
Gentoo, with vanilla kernel 6.2.8.

Which desktop environment and version?: 
i3 4.22.

Which session type?: 
X11.

Which application and version?: 
All, as far as I've seen.

IBus version?: 
1.5.28.

ibus-anthy version?: 
1.5.14.

Issue description:
With the last version of ibus-anthy I was using prior to upgrading, which I think was 1.5.13, my compose key worked fine. In this version, when I press the compose key with ibus-anthy as the input method, it shows a little window with the characters I'm typing as if it's preparing to enter the compose sequence just like it did before, but after I finish entering the sequence, no character appears. This affects every application I've tried. The compose key still works using my other enabled input method, xkb:us::eng, but I prefer to leave anthy on all the time for convenience (I switch between Japanese and English input frequently).

Steps to reproduce:
1. Enable ibus-anthy.
2. Try to enter any character using a compose sequence.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
No, it persists across both ibus-daemon restarts and whole restarts of X11 etc.

Do you see any errors when you run ibus-daemon with the verbose option?:
Yes:
```
(ibus-engine-anthy:16681): IBUS-WARNING **: 01:40:15.549: Not found compose resource The resource at “/org/freedesktop/ibus/compose/sequences” does not exist
```
My compose key sequences are in `~/.Xcompose`, which I thought ibus-anthy was supposed to utilize (and has in the past).

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
I haven't and it would be kind of awkward to, but I'm definitely willing if you think the problem could be my local configuration. I would end up copying a lot of the same config into the new account, though, so it wouldn't exactly rule that out per se.

**Comment by spinnylights** [comment]
It works! Thank you so much for the impresively rapid response. ^^

**Comment by DarkShadow44** [comment]
Is there plans for a release so this fixes makes it into distros?

**Comment by fujiwarat** [comment]
Sorry, I will release the new version next week.
