### ISSUE TITLE
1.5.10 Unable to Use on_off

### ISSUE THREAD

**Issue by NoSuck** [ibus/ibus-anthy#7]
Hello, and thank you for all you do.

```
■ uname -srvmo
Linux 4.16.7-1-ARCH #1 SMP PREEMPT Wed May 2 21:12:36 UTC 2018 x86_64 GNU/Linux
■ openbox --version | head -n1
Openbox 3.6.1
■ echo $XDG_SESSION_TYPE

```

(Note:  I run X11.)

I recently upgraded ibus-anthy from 1.5.9 to 1.5.10, and now the key combination configured for on_off no longer switches into IME mode.  Also, ibus-anthy configuration appears to be ignored.  (Every preference is reset to its default value--including the kana keymap, etc.)

If there is a way to provide better information, please let me know.

```
             OK         Problem    Problem
libibus      1.5.17-1   1.5.18-1   1.5.17-1
ibus         1.5.17-1   1.5.18-1   1.5.17-1
ibus-anthy   1.5.9-1    1.5.10-1   1.5.10-1
```

> Can you reproduce your problem when you restart ibus-daemon? (yes / no):
> (Run `ibus exit` and `ibus-daemon --xim &`)

Yes.

> Do you see any errors when you run ibus-daemon with the verbose option?:
> (Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

```
■ ibus-daemon --xim --verbose &
(ibus-ui-gtk3:2400): IBUS-WARNING **: 00:57:23.690: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:2400): IBUS-WARNING **: 00:57:23.708: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
```

(Note:  I also see these warnings when running the “OK” versions of libibus/ibus/ibus-anthy.

> Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

Is there an easy way to try this?  I would like to avoid creating user accounts.

**Comment by fujiwarat** [comment]
ping
